git:
  depth: 3
env:
  global:
  - AWS_DEFAULT_REGION: us-west-1
  - S3_PARAMS: '"--acl public-read --cache-control \"public,must-revalidate,proxy-revalidate,max-age=0\""'
  - OPUS_PARAMS: '"--disable-extra-programs --disable-doc --disable-hardening --enable-custom-modes"'
  - secure: UObz0fgdSZotmeU7dhVPqeCph+tVcx8cPP3qyPHqc12Iex2ofRQwPmf6a58xwKg17OeTPqffbVgmfKG6EhWm7GpZJdRja59JurzLg3T7idKK69kX52raTVbhGquJjZnP2SM/VaEPPwJFJR2n+vo8j2Fp1BZxNhCeA2Wbs2aSp9oKIGUGWhQ6+WL6RgkR4HzLzQS2Izo99d+yZrEcOWgaeERX/jSRcPglz/ixBwaxkupNheK0hZ28PQm2k1euTqwWE+kAzmaGCRmsWRdeRxfhuAxT7lE9/MS4tnMuysXB1vR2j0NE2GxxdGblPZqq2/GwDN4/8RKRw2yBs3Bgl1V7AUXU/tJi2HXJCgw9fNl9W8U1TuA6YcgqGSjlWueMttPAwEDMaSGpf1a4JaiBSMKcTlLlmJj+hL8U+Mh6D0xcf94cLtfM6UuSPKXGd+/EswBfc1sSDb3NZs2n51iOk2yv1RTkzHleCLMDO+pP7DV1Cpj7ryRuXYVoDJqL3/w7v1E4jGSWEJO/P1nAIKKAkguoVgPCzxBSXDjRM2zMmi35lERng5WoqdNBzJIb4liDHcrA/QllujTldfcP9aVGIPdqEPw4aO0/K7ujzXrxGRD/SS+kjKSou3eVGCcNqErXzDFj2+GP3cFSCS3e26OmZYfNyf4De8Y9/MkO0g0R9StxK+w=
matrix:
  include:
  - name: Linux x64
    dist: xenial
    language: c
    compiler: gcc
    addons:
      apt:
        packages:
        - gcc-4.8
    before_install:
    - pip install --user awscli
    - export PATH=$PATH:$HOME/.local/bin
    script:
    - "./autogen.sh"
    - CC="gcc-4.8" LDFLAGS="-Wl,--wrap,memcpy" ./configure $OPUS_PARAMS
    - make
    - strip .libs/libopus.so
    - git log --first-parent --pretty=format:%H HEAD~2..HEAD~1 > revision.git
    - aws s3 cp .libs/libopus.so s3://lwjgl-mips64/nightly/linux/x64/ $S3_PARAMS
    - aws s3 cp revision.git s3://lwjgl-mips64/nightly/linux/x64/libopus.so.git $S3_PARAMS
  - name: Linux arm32
    dist: xenial
    language: c
    compiler: gcc
    addons:
      apt:
        packages:
        - gcc-4.8-arm-linux-gnueabihf
        - libc6-dev-armhf-cross
    before_install:
    - pip install --user awscli
    - export PATH=$PATH:$HOME/.local/bin
    script:
    - "./autogen.sh"
    - CC="arm-linux-gnueabihf-gcc-4.8" ./configure $OPUS_PARAMS --build=x86_64-pc-linux-gnu
      --host=arm-linux-gnueabihf
    - make
    - arm-linux-gnueabihf-strip .libs/libopus.so
    - git log --first-parent --pretty=format:%H HEAD~2..HEAD~1 > revision.git
    - aws s3 cp .libs/libopus.so s3://lwjgl-mips64/nightly/linux/arm32/ $S3_PARAMS
    - aws s3 cp revision.git s3://lwjgl-mips64/nightly/linux/arm32/libopus.so.git
      $S3_PARAMS
  - name: Linux arm64
    dist: xenial
    language: c
    compiler: gcc
    addons:
      apt:
        packages:
        - gcc-5-aarch64-linux-gnu
        - libc6-dev-arm64-cross
    before_install:
    - pip install --user awscli
    - export PATH=$PATH:$HOME/.local/bin
    script:
    - "./autogen.sh"
    - CC="aarch64-linux-gnu-gcc-5" ./configure $OPUS_PARAMS --build=x86_64-pc-linux-gnu
      --host=aarch64-linux-gnu
    - make
    - aarch64-linux-gnu-strip .libs/libopus.so
    - git log --first-parent --pretty=format:%H HEAD~2..HEAD~1 > revision.git
    - aws s3 cp .libs/libopus.so s3://lwjgl-mips64/nightly/linux/arm64/ $S3_PARAMS
    - aws s3 cp revision.git s3://lwjgl-mips64/nightly/linux/arm64/libopus.so.git
      $S3_PARAMS
  - name: Linux mips64
    dist: xenial
    language: c
    compiler: gcc
    addons:
      apt:
        packages:
        - gcc-5-mips64el-linux-gnuabi64
        - libc6-dev-mips64el-cross
    before_install:
    - pip install --user awscli
    - export PATH=$PATH:$HOME/.local/bin
    script:
    - "./autogen.sh"
    - CC="mips64el-linux-gnuabi64-gcc-5" ./configure $OPUS_PARAMS --build=x86_64-pc-linux-gnu
      --host=mips64el-linux-gnuabi64
    - make
    - mips64el-linux-gnuabi64-strip .libs/libopus.so
    - git log --first-parent --pretty=format:%H HEAD~2..HEAD~1 > revision.git
    - aws s3 cp .libs/libopus.so s3://lwjgl-mips64/nightly/linux/mips64/ $S3_PARAMS
    - aws s3 cp revision.git s3://lwjgl-mips64/nightly/linux/mips64/libopus.so.git
      $S3_PARAMS
  - name: macOS
    language: objective-c
    osx_image: xcode11.3
    compiler: clang
    before_install:
    - brew update
    install:
    - brew install awscli
    script:
    - "./autogen.sh"
    - "./configure $OPUS_PARAMS"
    - make
    - strip -u -r .libs/libopus.dylib
    - git log --first-parent --pretty=format:%H HEAD~2..HEAD~1 > revision.git
    - aws s3 cp .libs/libopus.dylib s3://lwjgl-mips64/nightly/macosx/x64/ $S3_PARAMS
    - aws s3 cp revision.git s3://lwjgl-mips64/nightly/macosx/x64/libopus.dylib.git
      $S3_PARAMS
